version: '3.8'

services:
  
  redis:
    image: redis

  frontend:
    image: frontend
    build: ./frontend/
    ports:
      - 5000:5000

  backend:
    image: backend
    build: ./backend/
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    
    